### PR TITLE
Add modifiers for windicss

### PR DESCRIPTION
**Pull request by adzbuck**

### CODE REVIEW

**Comment by freddy38510** [comment]
Hello, thank you for opening this PR! I really appreciate that.

I will try to add some tests for modifiers for Windi and Tailwind Css.

**Comment by adzbuck** [comment]
Hi, I've been playing with quasar-app-extension-ssg and it seems great! However some of the classes wasn't being pulled through from criticalcss due to the special chars.

**Comment by freddy38510** [comment]
Does it sounds good to you ?

**Comment by adzbuck** [comment]
Looks perfect to me.

**Comment by freddy38510** [comment]
@adzbuck,

If you want to try if your classes are processed, I just published the latest version of quasar-app-extension-ssg with updated beastcss.

Don't forget that you can customize the beastcss options to whitelist some selectors.

**Pull request merged**
