### PR TITLE
Fix for encoded less than and greater than

### PR DESCRIPTION
**Pull request by adzbuck**
I didn't notice but Vue.JS encodes < and > with html entities `&lt; &gt;`
e.g. `ml-20px &lt;md:ml-20px &gt;md:ml-20px`

### CODE REVIEW

**Comment by adzbuck** [comment]
Tested this locally, and it's now pulling through.
It might be a thought to add [square brackets] as I know tailing jit uses them, and is a very popular css framework.

**Review by freddy38510 — CHANGES_REQUESTED** [review]
Could we create a single Regex that handle both cases ? I mean encoded or not encoded.

I guess it won't break the matching of `__6` and `__7` with CSS selectors.

**Comment by freddy38510** [comment]
> It might be a thought to add [square brackets] as I know tailing jit uses them, and is a very popular css framework.

Yes you are absolutely right, I agree with that.

Let's do this in a new pull request. Because it looks more like a new feature and the current commit is a fix.

**Comment by adzbuck** [comment]
Personally, I'd keep it separate as It's nice and readable, but happy to change it.

**Comment by adzbuck** [comment]
You also have a problem with the replace hitting 10, as 1 is going to replace before. How would you like to deal with that? You can reverse the order, or you could add suffix to the end e.g. __1n

**Comment by adzbuck** [comment]
- Added square brackets
- Merged the regex
- Reversed the order to prevent clash in replace e.g. __1 replacing  __10

**Comment by freddy38510** [comment]
> You also have a problem with the replace hitting 10, as 1 is going to replace before. How would you like to deal with that? You can reverse the order, or you could add suffix to the end e.g. __1n

This pattern `__1(?!0)` should do the trick for 1 to only replace `__1` and not `__10`.

Sorry to be annoying but it would be nice that square brackets are added in a new PR. Because I'm going to squash and merge this one. These are conventional commits to generate a proper changelog and release build.

**Comment by adzbuck** [comment]
> > You also have a problem with the replace hitting 10, as 1 is going to replace before. How would you like to deal with that? You can reverse the order, or you could add suffix to the end e.g. __1n
> 
> This pattern `__1(?!0)` should do the trick for 1 to only replace `__1` and not `__10`.
> 
> Sorry to be annoying but it would be nice that square brackets are added in a new PR. Because I'm going to squash and merge this one. These are conventional commits to generate a proper changelog and release build.

This could be a little dangerous as you could have md:0-mx, this would then not match any?
I've stopped being lazy(using github) and pulled the code and done a pr.

**Comment by freddy38510** [comment]
> * Added square brackets
> * Merged the regex
> * Reversed the order to prevent clash in replace e.g. __1 replacing  __10

Done in https://github.com/freddy38510/beastcss/pull/89 and https://github.com/freddy38510/beastcss/commit/65a12257a94a685ebf27c892423d56116422cc8d

**Pull request closed without merging**
